export const ADD_IDEA = "ADD_IDEA";
export const DELETE_IDEA = "DELETE_IDEA";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SET_STORED_IDEAS = "SET_STORED_IDEAS";
export const SPIN = 'SPIN';
export const SET_SELECTIONS = 'SET_SELECTIONS';